#!/bin/bash

#####################
# install brew
# https://brew.sh/index_ja.html

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

brew bundle -f $(cd $(dirname $0); pwd)/Brewfile

#####################
# key repeat & screenshot dir
# require reboot.

mkdir -p ~/Downloads/screenshots
defaults write com.apple.screencapture location ~/Downloads/screenshots

defaults write -g KeyRepeat -int 1
defaults write -g InitialKeyRepeat -int 10
killall SystemUIServer

#####################
# zsh install

sudo sh -c "echo '/usr/local/bin/zsh' >> /etc/shells"
chsh -s /usr/local/bin/zsh

# echo 'fpath=(/usr/local/share/zsh-completions $fpath)' >> ~/.zshrc
# mkdir ~/.ssh && chmod 700 ~/.ssh

# API rate limit exceeded for 対策
# http://yudoufu.hatenablog.jp/entry/2016/06/09/011754 -> private repoを取得するためには、repo権限が必要。
# https://rcmdnk.com/blog/2013/12/05/mac-homebrew/

# brew install httpie

#####################
# asdf

echo -e ". $(brew --prefix asdf)/asdf.sh" >> ~/.zshrc.local
source ~/.zshrc.local

for package in "golang ruby nodejs yarn python php perl terraform"
do
  asdf plugin add $package
  asdf install $package latest
  asdf global $package $(asdf list $package | tail -n 1)
done

#####################
# neovim

## sqlite が一緒に入るので
# echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.zshrc

pip3 install neovim

curl -O https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh
sh installer.sh ~/.cache/dein

:call dein#install()

#####################
# npm & xcenv

mkdir -p "$(nodenv root)/plugins"
git clone https://github.com/pine/nodenv-yarn-install.git "$(nodenv root)/plugins/nodenv-yarn-install"

npm install -g pure-prompt
sudo gem install xcode-install

#####################
## docker

open /Applications/Docker.app
docker run hello-world

######################
# GNU GLOBAL
# https://gist.github.com/haru-ake/b2273492813360afa8f7b6d3dcecca21

#brew install global --with-pygments --with-sqlite3
# cp /usr/local/etc/gtags.conf ~/.globalrc
# export XCENV_DO_NOT_SHIM_LIST="ctags"

